<?php

/**
 * SocialEngineSolutions
 *
 * @category   Application_Sesatoz
 * @package    Sesatoz
 * @copyright  Copyright 2018-2019 SocialEngineSolutions
 * @license    http://www.socialenginesolutions.com/license/
 * @version    $Id: defaultsettings.php  2018-10-05 00:00:00 SocialEngineSolutions $
 * @author     SocialEngineSolutions
 */

$db = Zend_Db_Table_Abstract::getDefaultAdapter();
$default_constants = array(
    'sesatoz_responsive_layout'=> '1',
    'sesatoz_body_background_image' => 'public/admin/blank.png',
    'sesatoz_user_photo_round' => '1',
    'sesatoz_left_columns_width' => '240px',
    'sesatoz_right_columns_width' => '240px',
    'sesatoz_header_design' => '1',
    'sesatoz_sidepanel_effect' => '2',
    'sesatoz_footer_background_image' => 'public/admin/blank.png',
    'sesatoz_header_background_color' => '#191919',
    'sesatoz_menu_logo_font_color' => '#FB0060',
    'sesatoz_mainmenu_background_color' => '#FB0060',
    'sesatoz_mainmenu_links_color' => '#FFFFFF',
    'sesatoz_mainmenu_links_hover_color' => '#FFFFFF',
    'sesatoz_minimenu_links_color' => '#FFFFFF',
    'sesatoz_minimenu_links_hover_color' => '#FFFFFF',
    'sesatoz_minimenu_icon_background_color' => '#5D5D5D',
    'sesatoz_minimenu_icon_background_active_color' => '#FB0060',
    'sesatoz_minimenu_icon_color' => '#FFFFFF',
    'sesatoz_minimenu_icon_active_color' => '#FFFFFF',
    'sesatoz_header_searchbox_background_color' => '#ECEFF1',
    'sesatoz_header_searchbox_text_color' => '#FFFFFF',
    'sesatoz_toppanel_userinfo_background_color' => '#FB0060',
    'sesatoz_toppanel_userinfo_font_color' => '#FFFFFF',
    'sesatoz_footer_background_color' => '#222222',
    'sesatoz_footer_links_color' => '#FFFFFF',
    'sesatoz_footer_links_hover_color' => '#FB0060',
    'sesatoz_theme_color' => '#FB0060',
    'sesatoz_body_background_color' => '#ECEFF1',
    'sesatoz_font_color' => '#243238',
    'sesatoz_font_color_light' => '#999999',
    'sesatoz_heading_color' => '#243238',
    'sesatoz_links_color' => '#243238',
    'sesatoz_links_hover_color' => '#FB0060',
    'sesatoz_content_header_background_color' => '#FFFFFF',
    'sesatoz_content_header_font_color' => '#243238',
    'sesatoz_content_background_color' => '#FFFFFF',
    'sesatoz_content_border_color' => '#EBECEE',
    'sesatoz_form_label_color' => '#243238',
    'sesatoz_input_background_color' => '#FFFFFF',
    'sesatoz_input_font_color' => '#6D6D6D',
    'sesatoz_input_border_color' => '#CACACA',
    'sesatoz_button_background_color' => '#FB0060',
    'sesatoz_button_background_color_hover' => '#243238',
    'sesatoz_button_font_color' => '#FFFFFF',
    'sesatoz_button_font_hover_color' => '#FFFFFF',
    'sesatoz_comment_background_color' => '#FDFDFD',
    'sesatoz_body_fontfamily' => 'Roboto',
    'sesatoz_body_fontsize' => '14px',
    'sesatoz_heading_fontfamily' => 'Roboto',
    'sesatoz_heading_fontsize' => '17px',
    'sesatoz_mainmenu_fontfamily' => 'Roboto',
    'sesatoz_mainmenu_fontsize' => '13px',
    'sesatoz_tab_fontfamily' => 'Roboto',
    'sesatoz_tab_fontsize' => '15px',
    'sesatoz_mainmenu_links_background_color_hover' => '#D90053'
);
Engine_Api::_()->sesatoz()->readWriteXML('', '', $default_constants);

//Quick links footer
$menuitem_id = $db->select()
                ->from('engine4_core_menuitems', 'id')
                ->limit(1)
                ->order('id DESC')
                ->query()
                ->fetchColumn();

$db->query('INSERT IGNORE INTO `engine4_core_menuitems` (`name`, `module`, `label`, `plugin`, `params`, `menu`, `submenu`, `enabled`, `custom`, `order`) VALUES
("custom_'.$menuitem_id++.'", "core", "Albums", "", \'{"uri":"albums","icon":""}\', "sesatoz_quicklinks_footer", "", 1, 1, 1),
("custom_'.$menuitem_id++.'", "core", "Blogs", "", \'{"uri":"blogs","icon":""}\', "sesatoz_quicklinks_footer", "", 1, 1, 2),
("custom_'.$menuitem_id++.'", "core", "Events", "", \'{"uri":"events"}\', "sesatoz_quicklinks_footer", "", 1, 1, 3),
("custom_'.$menuitem_id++.'", "core", "Videos", "", \'{"uri":"videos","icon":"","target":"","enabled":"1"}\', "sesatoz_quicklinks_footer", "", 1, 1, 4),
("custom_'.$menuitem_id++.'", "core", "Music", "", \'{"uri":"music/album/home","icon":"","target":"","enabled":"1"}\', "sesatoz_quicklinks_footer", "", 1, 1, 5);');

//Header Default Work
$content_id = $this->widgetCheck(array('widget_name' => 'sesatoz.header', 'page_id' => '1'));

$minimenu = $this->widgetCheck(array('widget_name' => 'core.menu-mini', 'page_id' => '1'));
$menulogo = $this->widgetCheck(array('widget_name' => 'core.menu-logo', 'page_id' => '1'));
$mainmenu = $this->widgetCheck(array('widget_name' => 'core.menu-main', 'page_id' => '1'));
$search = $this->widgetCheck(array('widget_name' => 'core.search-mini', 'page_id' => '1'));

$parent_content_id = $db->select()
        ->from('engine4_core_content', 'content_id')
        ->where('type = ?', 'container')
        ->where('page_id = ?', '1')
        ->where('name = ?', 'main')
        ->limit(1)
        ->query()
        ->fetchColumn();
if (empty($content_id)) {
  if($minimenu)
    $db->query('DELETE FROM `engine4_core_content` WHERE `engine4_core_content`.`content_id` = "'.$minimenu.'";');
  if($menulogo)
    $db->query('DELETE FROM `engine4_core_content` WHERE `engine4_core_content`.`content_id` = "'.$menulogo.'";');
  if($mainmenu)
    $db->query('DELETE FROM `engine4_core_content` WHERE `engine4_core_content`.`content_id` = "'.$mainmenu.'";');
  if($search)
    $db->query('DELETE FROM `engine4_core_content` WHERE `engine4_core_content`.`content_id` = "'.$search.'";');
  $db->insert('engine4_core_content', array(
      'type' => 'widget',
      'name' => 'sesatoz.header',
      'page_id' => 1,
      'parent_content_id' => $parent_content_id,
      'order' => 20,
  ));
}

//Footer Default Work
$footerContent_id = $this->widgetCheck(array('widget_name' => 'sesatoz.menu-footer', 'page_id' => '2'));
$footerMenu = $this->widgetCheck(array('widget_name' => 'core.menu-footer', 'page_id' => '2'));
$parent_content_id = $db->select()
        ->from('engine4_core_content', 'content_id')
        ->where('type = ?', 'container')
        ->where('page_id = ?', '2')
        ->where('name = ?', 'main')
        ->limit(1)
        ->query()
        ->fetchColumn();
if (empty($footerContent_id)) {
  if($footerMenu)
    $db->query('DELETE FROM `engine4_core_content` WHERE `engine4_core_content`.`content_id` = "'.$footerMenu.'";');

  $db->insert('engine4_core_content', array(
      'type' => 'widget',
      'name' => 'sesatoz.menu-footer',
      'page_id' => 2,
      'parent_content_id' => $parent_content_id,
      'order' => 10,
  ));
}

//Upload Banner images
$db->query('INSERT IGNORE INTO `engine4_sesatoz_banners` (`banner_name`, `creation_date`, `modified_date`, `enabled`) VALUES ("Member Home Page", "2016-11-21 15:45:57", "2016-11-21 15:45:57", 1);');

$db->query('INSERT IGNORE INTO `engine4_sesatoz_slides` (`slide_id`, `banner_id`, `title`, `title_button_color`, `description`, `description_button_color`, `file_type`, `file_id`, `status`, `extra_button_linkopen`, `extra_button`, `extra_button_text`, `extra_button_link`, `order`, `creation_date`, `modified_date`, `enabled`) VALUES
(1, 1, "Grow your network with us", "FFFFFF", "", "FFFFFF", "jpg", 26519, "1", 0, 0, "Read More", "", 0, "2016-11-21 15:46:41", "2016-11-21 16:23:07", 1),
(2, 1, "Join Your Favourite Groups", "FFFFFF", "", "FFFFFF", "jpg", 26520, "1", 0, 0, "Read More", "", 0, "2016-11-21 15:49:10", "2016-11-21 16:24:00", 1),
(3, 1, "Write To Share Your Thoughts", "FFFFFF", "", "FFFFFF", "jpg", 26518, "1", 0, 1, "Write New Blog", "blog/create", 0, "2016-11-21 15:50:06", "2016-11-21 16:25:32", 1);');
$this->uploadHomeBanner();


$page_table = Engine_Api::_()->getDbtable('pages', 'core');
$page_table_name = $page_table->info('name');

$content_table = Engine_Api::_()->getDbtable('content', 'core');
$content_table_name = $content_table->info('name');

//Login Page
$select = new Zend_Db_Select($db);
$page_login_id = $select
        ->from('engine4_core_pages', 'page_id')
        ->where('name = ?', 'user_auth_login')
        ->query()
        ->fetchColumn();
if ($page_login_id) {
  $db->query("UPDATE  `engine4_core_content` SET  `name` =  'sesatoz.login' WHERE  `engine4_core_content`.`name` ='core.content' AND `engine4_core_content`.`page_id` ='".$page_login_id."' LIMIT 1");
}

//Default theme color for custom theme
$db->query('INSERT IGNORE INTO `engine4_sesatoz_customthemes` (`customtheme_id`, `name`, `value`, `column_key`, `theme_id`, `default`) VALUES
(1, "Theme - 1", "1", "theme_color", 1, 0),
(2, "Theme - 1", "1", "custom_theme_color", 1, 0),
(4, "Theme - 1", "#191919", "sesatoz_header_background_color", 1, 0),
(5, "Theme - 1", "#FFD11B", "sesatoz_menu_logo_font_color", 1, 0),
(6, "Theme - 1", "#FFD11B", "sesatoz_mainmenu_background_color", 1, 0),
(7, "Theme - 1", "#191919", "sesatoz_mainmenu_links_color", 1, 0),
(8, "Theme - 1", "#191919", "sesatoz_mainmenu_links_hover_color", 1, 0),
(9, "Theme - 1", "#FFFFFF", "sesatoz_minimenu_links_color", 1, 0),
(10, "Theme - 1", "#191919", "sesatoz_minimenu_links_hover_color", 1, 0),
(11, "Theme - 1", "#5D5D5D", "sesatoz_minimenu_icon_background_color", 1, 0),
(12, "Theme - 1", "#FFD11B", "sesatoz_minimenu_icon_background_active_color", 1, 0),
(13, "Theme - 1", "#FFD11B", "sesatoz_minimenu_icon_color", 1, 0),
(14, "Theme - 1", "#191919", "sesatoz_minimenu_icon_active_color", 1, 0),
(15, "Theme - 1", "#FFFFFF", "sesatoz_header_searchbox_background_color", 1, 0),
(16, "Theme - 1", "#FFFFFF", "sesatoz_header_searchbox_text_color", 1, 0),
(17, "Theme - 1", "#191919", "sesatoz_toppanel_userinfo_background_color", 1, 0),
(18, "Theme - 1", "#FFFFFF", "sesatoz_toppanel_userinfo_font_color", 1, 0),
(19, "Theme - 1", "#222222", "sesatoz_footer_background_color", 1, 0),
(20, "Theme - 1", "#FFFFFF", "sesatoz_footer_links_color", 1, 0),
(21, "Theme - 1", "#FFD11B", "sesatoz_footer_links_hover_color", 1, 0),
(22, "Theme - 1", "#DDDDDD", "sesatoz_footer_border_color", 1, 0),
(23, "Theme - 1", "#FFD11B", "sesatoz_theme_color", 1, 0),
(24, "Theme - 1", "#ECEFF1", "sesatoz_body_background_color", 1, 0),
(25, "Theme - 1", "#191919", "sesatoz_font_color", 1, 0),
(26, "Theme - 1", "#999999", "sesatoz_font_color_light", 1, 0),
(27, "Theme - 1", "#191919", "sesatoz_heading_color", 1, 0),
(28, "Theme - 1", "#191919", "sesatoz_links_color", 1, 0),
(29, "Theme - 1", "#FFD11B", "sesatoz_links_hover_color", 1, 0),
(30, "Theme - 1", "#FFFFFF", "sesatoz_content_header_background_color", 1, 0),
(31, "Theme - 1", "#191919", "sesatoz_content_header_font_color", 1, 0),
(32, "Theme - 1", "#FFFFFF", "sesatoz_content_background_color", 1, 0),
(33, "Theme - 1", "#EBECEE", "sesatoz_content_border_color", 1, 0),
(34, "Theme - 1", "#191919", "sesatoz_form_label_color", 1, 0),
(35, "Theme - 1", "#FFFFFF", "sesatoz_input_background_color", 1, 0),
(36, "Theme - 1", "#6D6D6D", "sesatoz_input_font_color", 1, 0),
(37, "Theme - 1", "#CACACA", "sesatoz_input_border_color", 1, 0),
(38, "Theme - 1", "#FFD11B", "sesatoz_button_background_color", 1, 0),
(39, "Theme - 1", "#191919", "sesatoz_button_background_color_hover", 1, 0),
(40, "Theme - 1", "#191919", "sesatoz_button_font_color", 1, 0),
(41, "Theme - 1", "#FFFFFF", "sesatoz_button_font_hover_color", 1, 0),
(42, "Theme - 1", "#FDFDFD", "sesatoz_comment_background_color", 1, 0),
(43, "Theme - 2", "2", "theme_color", 2, 0),
(44, "Theme - 2", "1", "custom_theme_color", 2, 0),
(46, "Theme - 2", "#191919", "sesatoz_header_background_color", 2, 0),
(47, "Theme - 2", "#FB0060", "sesatoz_menu_logo_font_color", 2, 0),
(48, "Theme - 2", "#FB0060", "sesatoz_mainmenu_background_color", 2, 0),
(49, "Theme - 2", "#FFFFFF", "sesatoz_mainmenu_links_color", 2, 0),
(50, "Theme - 2", "#FFFFFF", "sesatoz_mainmenu_links_hover_color", 2, 0),
(51, "Theme - 2", "#FFFFFF", "sesatoz_minimenu_links_color", 2, 0),
(52, "Theme - 2", "#FB0060", "sesatoz_minimenu_links_hover_color", 2, 0),
(53, "Theme - 2", "#5D5D5D", "sesatoz_minimenu_icon_background_color", 2, 0),
(54, "Theme - 2", "#FB0060", "sesatoz_minimenu_icon_background_active_color", 2, 0),
(55, "Theme - 2", "#FB0060", "sesatoz_minimenu_icon_color", 2, 0),
(56, "Theme - 2", "#FFFFFF", "sesatoz_minimenu_icon_active_color", 2, 0),
(57, "Theme - 2", "#ECEFF1", "sesatoz_header_searchbox_background_color", 2, 0),
(58, "Theme - 2", "#FFFFFF", "sesatoz_header_searchbox_text_color", 2, 0),
(59, "Theme - 2", "#FB0060", "sesatoz_toppanel_userinfo_background_color", 2, 0),
(60, "Theme - 2", "#FFFFFF", "sesatoz_toppanel_userinfo_font_color", 2, 0),
(61, "Theme - 2", "#222222", "sesatoz_footer_background_color", 2, 0),
(62, "Theme - 2", "#FFFFFF", "sesatoz_footer_links_color", 2, 0),
(63, "Theme - 2", "#FB0060", "sesatoz_footer_links_hover_color", 2, 0),
(64, "Theme - 2", "#DDDDDD", "sesatoz_footer_border_color", 2, 0),
(65, "Theme - 2", "#FB0060", "sesatoz_theme_color", 2, 0),
(66, "Theme - 2", "#ECEFF1", "sesatoz_body_background_color", 2, 0),
(67, "Theme - 2", "#243238", "sesatoz_font_color", 2, 0),
(68, "Theme - 2", "#999999", "sesatoz_font_color_light", 2, 0),
(69, "Theme - 2", "#243238", "sesatoz_heading_color", 2, 0),
(70, "Theme - 2", "#243238", "sesatoz_links_color", 2, 0),
(71, "Theme - 2", "#FB0060", "sesatoz_links_hover_color", 2, 0),
(72, "Theme - 2", "#FFFFFF", "sesatoz_content_header_background_color", 2, 0),
(73, "Theme - 2", "#243238", "sesatoz_content_header_font_color", 2, 0),
(74, "Theme - 2", "#FFFFFF", "sesatoz_content_background_color", 2, 0),
(75, "Theme - 2", "#EBECEE", "sesatoz_content_border_color", 2, 0),
(76, "Theme - 2", "#243238", "sesatoz_form_label_color", 2, 0),
(77, "Theme - 2", "#FFFFFF", "sesatoz_input_background_color", 2, 0),
(78, "Theme - 2", "#6D6D6D", "sesatoz_input_font_color", 2, 0),
(79, "Theme - 2", "#CACACA", "sesatoz_input_border_color", 2, 0),
(80, "Theme - 2", "#243238", "sesatoz_button_background_color", 2, 0),
(81, "Theme - 2", "#243238", "sesatoz_button_background_color_hover", 2, 0),
(82, "Theme - 2", "#FFFFFF", "sesatoz_button_font_color", 2, 0),
(83, "Theme - 2", "#FFFFFF", "sesatoz_button_font_hover_color", 2, 0),
(84, "Theme - 2", "#FDFDFD", "sesatoz_comment_background_color", 2, 0),
(85, "Theme - 3", "3", "theme_color", 3, 0),
(86, "Theme - 3", "1", "custom_theme_color", 3, 0),
(88, "Theme - 3", "#191919", "sesatoz_header_background_color", 3, 0),
(89, "Theme - 3", "#FF1D23", "sesatoz_menu_logo_font_color", 3, 0),
(90, "Theme - 3", "#FF1D23", "sesatoz_mainmenu_background_color", 3, 0),
(91, "Theme - 3", "#FFFFFF", "sesatoz_mainmenu_links_color", 3, 0),
(92, "Theme - 3", "#FFFFFF", "sesatoz_mainmenu_links_hover_color", 3, 0),
(93, "Theme - 3", "#FFFFFF", "sesatoz_minimenu_links_color", 3, 0),
(94, "Theme - 3", "#FF1D23", "sesatoz_minimenu_links_hover_color", 3, 0),
(95, "Theme - 3", "#5D5D5D", "sesatoz_minimenu_icon_background_color", 3, 0),
(96, "Theme - 3", "#FF1D23", "sesatoz_minimenu_icon_background_active_color", 3, 0),
(97, "Theme - 3", "#FF1D23", "sesatoz_minimenu_icon_color", 3, 0),
(98, "Theme - 3", "#FFFFFF", "sesatoz_minimenu_icon_active_color", 3, 0),
(99, "Theme - 3", "#ECEFF1", "sesatoz_header_searchbox_background_color", 3, 0),
(100, "Theme - 3", "#FFFFFF", "sesatoz_header_searchbox_text_color", 3, 0),
(101, "Theme - 3", "#FF1D23", "sesatoz_toppanel_userinfo_background_color", 3, 0),
(102, "Theme - 3", "#FFFFFF", "sesatoz_toppanel_userinfo_font_color", 3, 0),
(103, "Theme - 3", "#222222", "sesatoz_footer_background_color", 3, 0),
(104, "Theme - 3", "#FFFFFF", "sesatoz_footer_links_color", 3, 0),
(105, "Theme - 3", "#FF1D23", "sesatoz_footer_links_hover_color", 3, 0),
(106, "Theme - 3", "#DDDDDD", "sesatoz_footer_border_color", 3, 0),
(107, "Theme - 3", "#FF1D23", "sesatoz_theme_color", 3, 0),
(108, "Theme - 3", "#ECEFF1", "sesatoz_body_background_color", 3, 0),
(109, "Theme - 3", "#243238", "sesatoz_font_color", 3, 0),
(110, "Theme - 3", "#999999", "sesatoz_font_color_light", 3, 0),
(111, "Theme - 3", "#243238", "sesatoz_heading_color", 3, 0),
(112, "Theme - 3", "#243238", "sesatoz_links_color", 3, 0),
(113, "Theme - 3", "#FF1D23", "sesatoz_links_hover_color", 3, 0),
(114, "Theme - 3", "#FFFFFF", "sesatoz_content_header_background_color", 3, 0),
(115, "Theme - 3", "#243238", "sesatoz_content_header_font_color", 3, 0),
(116, "Theme - 3", "#FFFFFF", "sesatoz_content_background_color", 3, 0),
(117, "Theme - 3", "#EBECEE", "sesatoz_content_border_color", 3, 0),
(118, "Theme - 3", "#243238", "sesatoz_form_label_color", 3, 0),
(119, "Theme - 3", "#FFFFFF", "sesatoz_input_background_color", 3, 0),
(120, "Theme - 3", "#6D6D6D", "sesatoz_input_font_color", 3, 0),
(121, "Theme - 3", "#CACACA", "sesatoz_input_border_color", 3, 0),
(122, "Theme - 3", "#FF1D23", "sesatoz_button_background_color", 3, 0),
(123, "Theme - 3", "#243238", "sesatoz_button_background_color_hover", 3, 0),
(124, "Theme - 3", "#FFFFFF", "sesatoz_button_font_color", 3, 0),
(125, "Theme - 3", "#FFFFFF", "sesatoz_button_font_hover_color", 3, 0),
(126, "Theme - 3", "#FDFDFD", "sesatoz_comment_background_color", 3, 0),
(127, "Theme - 4", "4", "theme_color", 4, 0),
(128, "Theme - 4", "1", "custom_theme_color", 4, 0),
(130, "Theme - 4", "#191919", "sesatoz_header_background_color", 4, 0),
(131, "Theme - 4", "#FF9800", "sesatoz_menu_logo_font_color", 4, 0),
(132, "Theme - 4", "#FF9800", "sesatoz_mainmenu_background_color", 4, 0),
(133, "Theme - 4", "#FFFFFF", "sesatoz_mainmenu_links_color", 4, 0),
(134, "Theme - 4", "#FFFFFF", "sesatoz_mainmenu_links_hover_color", 4, 0),
(135, "Theme - 4", "#FFFFFF", "sesatoz_minimenu_links_color", 4, 0),
(136, "Theme - 4", "#FF9800", "sesatoz_minimenu_links_hover_color", 4, 0),
(137, "Theme - 4", "#5D5D5D", "sesatoz_minimenu_icon_background_color", 4, 0),
(138, "Theme - 4", "#FF9800", "sesatoz_minimenu_icon_background_active_color", 4, 0),
(139, "Theme - 4", "#FF9800", "sesatoz_minimenu_icon_color", 4, 0),
(140, "Theme - 4", "#FFFFFF", "sesatoz_minimenu_icon_active_color", 4, 0),
(141, "Theme - 4", "#ECEFF1", "sesatoz_header_searchbox_background_color", 4, 0),
(142, "Theme - 4", "#FFFFFF", "sesatoz_header_searchbox_text_color", 4, 0),
(143, "Theme - 4", "#FF9800", "sesatoz_toppanel_userinfo_background_color", 4, 0),
(144, "Theme - 4", "#FFFFFF", "sesatoz_toppanel_userinfo_font_color", 4, 0),
(145, "Theme - 4", "#222222", "sesatoz_footer_background_color", 4, 0),
(146, "Theme - 4", "#FFFFFF", "sesatoz_footer_links_color", 4, 0),
(147, "Theme - 4", "#FF9800", "sesatoz_footer_links_hover_color", 4, 0),
(148, "Theme - 4", "#DDDDDD", "sesatoz_footer_border_color", 4, 0),
(149, "Theme - 4", "#FF9800", "sesatoz_theme_color", 4, 0),
(150, "Theme - 4", "#ECEFF1", "sesatoz_body_background_color", 4, 0),
(151, "Theme - 4", "#243238", "sesatoz_font_color", 4, 0),
(152, "Theme - 4", "#999999", "sesatoz_font_color_light", 4, 0),
(153, "Theme - 4", "#243238", "sesatoz_heading_color", 4, 0),
(154, "Theme - 4", "#243238", "sesatoz_links_color", 4, 0),
(155, "Theme - 4", "#FF9800", "sesatoz_links_hover_color", 4, 0),
(156, "Theme - 4", "#FFFFFF", "sesatoz_content_header_background_color", 4, 0),
(157, "Theme - 4", "#243238", "sesatoz_content_header_font_color", 4, 0),
(158, "Theme - 4", "#FFFFFF", "sesatoz_content_background_color", 4, 0),
(159, "Theme - 4", "#EBECEE", "sesatoz_content_border_color", 4, 0),
(160, "Theme - 4", "#243238", "sesatoz_form_label_color", 4, 0),
(161, "Theme - 4", "#FFFFFF", "sesatoz_input_background_color", 4, 0),
(162, "Theme - 4", "#6D6D6D", "sesatoz_input_font_color", 4, 0),
(163, "Theme - 4", "#CACACA", "sesatoz_input_border_color", 4, 0),
(164, "Theme - 4", "#FF9800", "sesatoz_button_background_color", 4, 0),
(165, "Theme - 4", "#243238", "sesatoz_button_background_color_hover", 4, 0),
(166, "Theme - 4", "#FFFFFF", "sesatoz_button_font_color", 4, 0),
(167, "Theme - 4", "#FFFFFF", "sesatoz_button_font_hover_color", 4, 0),
(168, "Theme - 4", "#FDFDFD", "sesatoz_comment_background_color", 4, 0),
(169, "Theme - 5", "6", "theme_color", 6, 0),
(170, "Theme - 5", "1", "custom_theme_color", 6, 0),
(172, "Theme - 5", "#191919", "sesatoz_header_background_color", 6, 0),
(173, "Theme - 5", "#03A9F4", "sesatoz_menu_logo_font_color", 6, 0),
(174, "Theme - 5", "#03A9F4", "sesatoz_mainmenu_background_color", 6, 0),
(175, "Theme - 5", "#FFFFFF", "sesatoz_mainmenu_links_color", 6, 0),
(176, "Theme - 5", "#FFFFFF", "sesatoz_mainmenu_links_hover_color", 6, 0),
(177, "Theme - 5", "#FFFFFF", "sesatoz_minimenu_links_color", 6, 0),
(178, "Theme - 5", "#03A9F4", "sesatoz_minimenu_links_hover_color", 6, 0),
(179, "Theme - 5", "#5D5D5D", "sesatoz_minimenu_icon_background_color", 6, 0),
(180, "Theme - 5", "#03A9F4", "sesatoz_minimenu_icon_background_active_color", 6, 0),
(181, "Theme - 5", "#03A9F4", "sesatoz_minimenu_icon_color", 6, 0),
(182, "Theme - 5", "#FFFFFF", "sesatoz_minimenu_icon_active_color", 6, 0),
(183, "Theme - 5", "#ECEFF1", "sesatoz_header_searchbox_background_color", 6, 0),
(184, "Theme - 5", "#FFFFFF", "sesatoz_header_searchbox_text_color", 6, 0),
(185, "Theme - 5", "#03A9F4", "sesatoz_toppanel_userinfo_background_color", 6, 0),
(186, "Theme - 5", "#FFFFFF", "sesatoz_toppanel_userinfo_font_color", 6, 0),
(187, "Theme - 5", "#222222", "sesatoz_footer_background_color", 6, 0),
(188, "Theme - 5", "#FFFFFF", "sesatoz_footer_links_color", 6, 0),
(189, "Theme - 5", "#03A9F4", "sesatoz_footer_links_hover_color", 6, 0),
(190, "Theme - 5", "#DDDDDD", "sesatoz_footer_border_color", 6, 0),
(191, "Theme - 5", "#03A9F4", "sesatoz_theme_color", 6, 0),
(192, "Theme - 5", "#ECEFF1", "sesatoz_body_background_color", 6, 0),
(193, "Theme - 5", "#243238", "sesatoz_font_color", 6, 0),
(194, "Theme - 5", "#999999", "sesatoz_font_color_light", 6, 0),
(195, "Theme - 5", "#243238", "sesatoz_heading_color", 6, 0),
(196, "Theme - 5", "#243238", "sesatoz_links_color", 6, 0),
(197, "Theme - 5", "#03A9F4", "sesatoz_links_hover_color", 6, 0),
(198, "Theme - 5", "#FFFFFF", "sesatoz_content_header_background_color", 6, 0),
(199, "Theme - 5", "#243238", "sesatoz_content_header_font_color", 6, 0),
(200, "Theme - 5", "#FFFFFF", "sesatoz_content_background_color", 6, 0),
(201, "Theme - 5", "#EBECEE", "sesatoz_content_border_color", 6, 0),
(202, "Theme - 5", "#243238", "sesatoz_form_label_color", 6, 0),
(203, "Theme - 5", "#FFFFFF", "sesatoz_input_background_color", 6, 0),
(204, "Theme - 5", "#6D6D6D", "sesatoz_input_font_color", 6, 0),
(205, "Theme - 5", "#CACACA", "sesatoz_input_border_color", 6, 0),
(206, "Theme - 5", "#03A9F4", "sesatoz_button_background_color", 6, 0),
(207, "Theme - 5", "#243238", "sesatoz_button_background_color_hover", 6, 0),
(208, "Theme - 5", "#FFFFFF", "sesatoz_button_font_color", 6, 0),
(209, "Theme - 5", "#FFFFFF", "sesatoz_button_font_hover_color", 6, 0),
(210, "Theme - 5", "#FDFDFD", "sesatoz_comment_background_color", 6, 0),
(211, "Theme - 6", "7", "theme_color", 7, 0),
(212, "Theme - 6", "1", "custom_theme_color", 7, 0),
(214, "Theme - 6", "#191919", "sesatoz_header_background_color", 7, 0),
(215, "Theme - 6", "#8BC34A", "sesatoz_menu_logo_font_color", 7, 0),
(216, "Theme - 6", "#8BC34A", "sesatoz_mainmenu_background_color", 7, 0),
(217, "Theme - 6", "#FFFFFF", "sesatoz_mainmenu_links_color", 7, 0),
(218, "Theme - 6", "#FFFFFF", "sesatoz_mainmenu_links_hover_color", 7, 0),
(219, "Theme - 6", "#FFFFFF", "sesatoz_minimenu_links_color", 7, 0),
(220, "Theme - 6", "#8BC34A", "sesatoz_minimenu_links_hover_color", 7, 0),
(221, "Theme - 6", "#5D5D5D", "sesatoz_minimenu_icon_background_color", 7, 0),
(222, "Theme - 6", "#8BC34A", "sesatoz_minimenu_icon_background_active_color", 7, 0),
(223, "Theme - 6", "#8BC34A", "sesatoz_minimenu_icon_color", 7, 0),
(224, "Theme - 6", "#FFFFFF", "sesatoz_minimenu_icon_active_color", 7, 0),
(225, "Theme - 6", "#ECEFF1", "sesatoz_header_searchbox_background_color", 7, 0),
(226, "Theme - 6", "#FFFFFF", "sesatoz_header_searchbox_text_color", 7, 0),
(227, "Theme - 6", "#8BC34A", "sesatoz_toppanel_userinfo_background_color", 7, 0),
(228, "Theme - 6", "#FFFFFF", "sesatoz_toppanel_userinfo_font_color", 7, 0),
(229, "Theme - 6", "#222222", "sesatoz_footer_background_color", 7, 0),
(230, "Theme - 6", "#FFFFFF", "sesatoz_footer_links_color", 7, 0),
(231, "Theme - 6", "#8BC34A", "sesatoz_footer_links_hover_color", 7, 0),
(232, "Theme - 6", "#DDDDDD", "sesatoz_footer_border_color", 7, 0),
(233, "Theme - 6", "#8BC34A", "sesatoz_theme_color", 7, 0),
(234, "Theme - 6", "#ECEFF1", "sesatoz_body_background_color", 7, 0),
(235, "Theme - 6", "#243238", "sesatoz_font_color", 7, 0),
(236, "Theme - 6", "#999999", "sesatoz_font_color_light", 7, 0),
(237, "Theme - 6", "#243238", "sesatoz_heading_color", 7, 0),
(238, "Theme - 6", "#243238", "sesatoz_links_color", 7, 0),
(239, "Theme - 6", "#8BC34A", "sesatoz_links_hover_color", 7, 0),
(240, "Theme - 6", "#FFFFFF", "sesatoz_content_header_background_color", 7, 0),
(241, "Theme - 6", "#243238", "sesatoz_content_header_font_color", 7, 0),
(242, "Theme - 6", "#FFFFFF", "sesatoz_content_background_color", 7, 0),
(243, "Theme - 6", "#EBECEE", "sesatoz_content_border_color", 7, 0),
(244, "Theme - 6", "#243238", "sesatoz_form_label_color", 7, 0),
(245, "Theme - 6", "#FFFFFF", "sesatoz_input_background_color", 7, 0),
(246, "Theme - 6", "#6D6D6D", "sesatoz_input_font_color", 7, 0),
(247, "Theme - 6", "#CACACA", "sesatoz_input_border_color", 7, 0),
(248, "Theme - 6", "#8BC34A", "sesatoz_button_background_color", 7, 0),
(249, "Theme - 6", "#243238", "sesatoz_button_background_color_hover", 7, 0),
(250, "Theme - 6", "#FFFFFF", "sesatoz_button_font_color", 7, 0),
(251, "Theme - 6", "#FFFFFF", "sesatoz_button_font_hover_color", 7, 0),
(252, "Theme - 6", "#FDFDFD", "sesatoz_comment_background_color", 7, 0),
(253, "Theme - 7", "8", "theme_color", 8, 0),
(254, "Theme - 7", "1", "custom_theme_color", 8, 0),
(256, "Theme - 7", "#222428", "sesatoz_header_background_color", 8, 0),
(257, "Theme - 7", "#FFD11B", "sesatoz_menu_logo_font_color", 8, 0),
(258, "Theme - 7", "#FFD11B", "sesatoz_mainmenu_background_color", 8, 0),
(259, "Theme - 7", "#191919", "sesatoz_mainmenu_links_color", 8, 0),
(260, "Theme - 7", "#191919", "sesatoz_mainmenu_links_hover_color", 8, 0),
(261, "Theme - 7", "#FFFFFF", "sesatoz_minimenu_links_color", 8, 0),
(262, "Theme - 7", "#FFD11B", "sesatoz_minimenu_links_hover_color", 8, 0),
(263, "Theme - 7", "#36383D", "sesatoz_minimenu_icon_background_color", 8, 0),
(264, "Theme - 7", "#FFD11B", "sesatoz_minimenu_icon_background_active_color", 8, 0),
(265, "Theme - 7", "#FFD11B", "sesatoz_minimenu_icon_color", 8, 0),
(266, "Theme - 7", "#191919", "sesatoz_minimenu_icon_active_color", 8, 0),
(267, "Theme - 7", "#36383D", "sesatoz_header_searchbox_background_color", 8, 0),
(268, "Theme - 7", "#FFFFFF", "sesatoz_header_searchbox_text_color", 8, 0),
(269, "Theme - 7", "#FFD11B", "sesatoz_toppanel_userinfo_background_color", 8, 0),
(270, "Theme - 7", "#FFFFFF", "sesatoz_toppanel_userinfo_font_color", 8, 0),
(271, "Theme - 7", "#222222", "sesatoz_footer_background_color", 8, 0),
(272, "Theme - 7", "#B3B3B3", "sesatoz_footer_links_color", 8, 0),
(273, "Theme - 7", "#FFD11B", "sesatoz_footer_links_hover_color", 8, 0),
(274, "Theme - 7", "#FFD11B", "sesatoz_footer_border_color", 8, 0),
(275, "Theme - 7", "#FFD11B", "sesatoz_theme_color", 8, 0),
(276, "Theme - 7", "#111418", "sesatoz_body_background_color", 8, 0),
(277, "Theme - 7", "#F1F1F1", "sesatoz_font_color", 8, 0),
(278, "Theme - 7", "#DDDDDD", "sesatoz_font_color_light", 8, 0),
(279, "Theme - 7", "#FFFFFF", "sesatoz_heading_color", 8, 0),
(280, "Theme - 7", "#FFFFFF", "sesatoz_links_color", 8, 0),
(281, "Theme - 7", "#FFD11B", "sesatoz_links_hover_color", 8, 0),
(282, "Theme - 7", "#222428", "sesatoz_content_header_background_color", 8, 0),
(283, "Theme - 7", "#FFFFFF", "sesatoz_content_header_font_color", 8, 0),
(284, "Theme - 7", "#222428", "sesatoz_content_background_color", 8, 0),
(285, "Theme - 7", "#36383D", "sesatoz_content_border_color", 8, 0),
(286, "Theme - 7", "#FFFFFF", "sesatoz_form_label_color", 8, 0),
(287, "Theme - 7", "#222428", "sesatoz_input_background_color", 8, 0),
(288, "Theme - 7", "#FFFFFF", "sesatoz_input_font_color", 8, 0),
(289, "Theme - 7", "#36383D", "sesatoz_input_border_color", 8, 0),
(290, "Theme - 7", "#FFD11B", "sesatoz_button_background_color", 8, 0),
(291, "Theme - 7", "#FFE11C", "sesatoz_button_background_color_hover", 8, 0),
(292, "Theme - 7", "#222428", "sesatoz_button_font_color", 8, 0),
(293, "Theme - 7", "#FFFFFF", "sesatoz_button_font_hover_color", 8, 0),
(294, "Theme - 7", "#1E1F23", "sesatoz_comment_background_color", 8, 0),
(295, "Theme - 8", "9", "theme_color", 9, 0),
(296, "Theme - 8", "1", "custom_theme_color", 9, 0),
(298, "Theme - 8", "#222428", "sesatoz_header_background_color", 9, 0),
(299, "Theme - 8", "#FB0060", "sesatoz_menu_logo_font_color", 9, 0),
(300, "Theme - 8", "#FB0060", "sesatoz_mainmenu_background_color", 9, 0),
(301, "Theme - 8", "#FFFFFF", "sesatoz_mainmenu_links_color", 9, 0),
(302, "Theme - 8", "#191919", "sesatoz_mainmenu_links_hover_color", 9, 0),
(303, "Theme - 8", "#FFFFFF", "sesatoz_minimenu_links_color", 9, 0),
(304, "Theme - 8", "#FB0060", "sesatoz_minimenu_links_hover_color", 9, 0),
(305, "Theme - 8", "#36383D", "sesatoz_minimenu_icon_background_color", 9, 0),
(306, "Theme - 8", "#FB0060", "sesatoz_minimenu_icon_background_active_color", 9, 0),
(307, "Theme - 8", "#FB0060", "sesatoz_minimenu_icon_color", 9, 0),
(308, "Theme - 8", "#191919", "sesatoz_minimenu_icon_active_color", 9, 0),
(309, "Theme - 8", "#36383D", "sesatoz_header_searchbox_background_color", 9, 0),
(310, "Theme - 8", "#FFFFFF", "sesatoz_header_searchbox_text_color", 9, 0),
(311, "Theme - 8", "#FB0060", "sesatoz_toppanel_userinfo_background_color", 9, 0),
(312, "Theme - 8", "#FFFFFF", "sesatoz_toppanel_userinfo_font_color", 9, 0),
(313, "Theme - 8", "#222222", "sesatoz_footer_background_color", 9, 0),
(314, "Theme - 8", "#B3B3B3", "sesatoz_footer_links_color", 9, 0),
(315, "Theme - 8", "#FB0060", "sesatoz_footer_links_hover_color", 9, 0),
(316, "Theme - 8", "#FB0060", "sesatoz_footer_border_color", 9, 0),
(317, "Theme - 8", "#FB0060", "sesatoz_theme_color", 9, 0),
(318, "Theme - 8", "#111418", "sesatoz_body_background_color", 9, 0),
(319, "Theme - 8", "#F1F1F1", "sesatoz_font_color", 9, 0),
(320, "Theme - 8", "#DDDDDD", "sesatoz_font_color_light", 9, 0),
(321, "Theme - 8", "#FFFFFF", "sesatoz_heading_color", 9, 0),
(322, "Theme - 8", "#FFFFFF", "sesatoz_links_color", 9, 0),
(323, "Theme - 8", "#FB0060", "sesatoz_links_hover_color", 9, 0),
(324, "Theme - 8", "#222428", "sesatoz_content_header_background_color", 9, 0),
(325, "Theme - 8", "#FFFFFF", "sesatoz_content_header_font_color", 9, 0),
(326, "Theme - 8", "#222428", "sesatoz_content_background_color", 9, 0),
(327, "Theme - 8", "#36383D", "sesatoz_content_border_color", 9, 0),
(328, "Theme - 8", "#FFFFFF", "sesatoz_form_label_color", 9, 0),
(329, "Theme - 8", "#222428", "sesatoz_input_background_color", 9, 0),
(330, "Theme - 8", "#FFFFFF", "sesatoz_input_font_color", 9, 0),
(331, "Theme - 8", "#36383D", "sesatoz_input_border_color", 9, 0),
(332, "Theme - 8", "#FB0060", "sesatoz_button_background_color", 9, 0),
(333, "Theme - 8", "#FB0060", "sesatoz_button_background_color_hover", 9, 0),
(334, "Theme - 8", "#FFFFFF", "sesatoz_button_font_color", 9, 0),
(335, "Theme - 8", "#FFFFFF", "sesatoz_button_font_hover_color", 9, 0),
(336, "Theme - 8", "#1E1F23", "sesatoz_comment_background_color", 9, 0),
(337, "Theme - 9", "10", "theme_color", 10, 0),
(338, "Theme - 9", "496", "custom_theme_color", 10, 0),
(340, "Theme - 9", "#222428", "sesatoz_header_background_color", 10, 0),
(341, "Theme - 9", "#FF1D23", "sesatoz_menu_logo_font_color", 10, 0),
(342, "Theme - 9", "#FF1D23", "sesatoz_mainmenu_background_color", 10, 0),
(343, "Theme - 9", "#FFFFFF", "sesatoz_mainmenu_links_color", 10, 0),
(344, "Theme - 9", "#191919", "sesatoz_mainmenu_links_hover_color", 10, 0),
(345, "Theme - 9", "#FFFFFF", "sesatoz_minimenu_links_color", 10, 0),
(346, "Theme - 9", "#FF1D23", "sesatoz_minimenu_links_hover_color", 10, 0),
(347, "Theme - 9", "#36383D", "sesatoz_minimenu_icon_background_color", 10, 0),
(348, "Theme - 9", "#FF1D23", "sesatoz_minimenu_icon_background_active_color", 10, 0),
(349, "Theme - 9", "#FF1D23", "sesatoz_minimenu_icon_color", 10, 0),
(350, "Theme - 9", "#191919", "sesatoz_minimenu_icon_active_color", 10, 0),
(351, "Theme - 9", "#36383D", "sesatoz_header_searchbox_background_color", 10, 0),
(352, "Theme - 9", "#FFFFFF", "sesatoz_header_searchbox_text_color", 10, 0),
(353, "Theme - 9", "#FF1D23", "sesatoz_toppanel_userinfo_background_color", 10, 0),
(354, "Theme - 9", "#FFFFFF", "sesatoz_toppanel_userinfo_font_color", 10, 0),
(355, "Theme - 9", "#222222", "sesatoz_footer_background_color", 10, 0),
(356, "Theme - 9", "#B3B3B3", "sesatoz_footer_links_color", 10, 0),
(357, "Theme - 9", "#FF1D23", "sesatoz_footer_links_hover_color", 10, 0),
(358, "Theme - 9", "#FB0060", "sesatoz_footer_border_color", 10, 0),
(359, "Theme - 9", "#FF1D23", "sesatoz_theme_color", 10, 0),
(360, "Theme - 9", "#111418", "sesatoz_body_background_color", 10, 0),
(361, "Theme - 9", "#F1F1F1", "sesatoz_font_color", 10, 0),
(362, "Theme - 9", "#DDDDDD", "sesatoz_font_color_light", 10, 0),
(363, "Theme - 9", "#FFFFFF", "sesatoz_heading_color", 10, 0),
(364, "Theme - 9", "#FFFFFF", "sesatoz_links_color", 10, 0),
(365, "Theme - 9", "#FF1D23", "sesatoz_links_hover_color", 10, 0),
(366, "Theme - 9", "#222428", "sesatoz_content_header_background_color", 10, 0),
(367, "Theme - 9", "#FFFFFF", "sesatoz_content_header_font_color", 10, 0),
(368, "Theme - 9", "#222428", "sesatoz_content_background_color", 10, 0),
(369, "Theme - 9", "#36383D", "sesatoz_content_border_color", 10, 0),
(370, "Theme - 9", "#FFFFFF", "sesatoz_form_label_color", 10, 0),
(371, "Theme - 9", "#222428", "sesatoz_input_background_color", 10, 0),
(372, "Theme - 9", "#FFFFFF", "sesatoz_input_font_color", 10, 0),
(373, "Theme - 9", "#36383D", "sesatoz_input_border_color", 10, 0),
(374, "Theme - 9", "#FF1D23", "sesatoz_button_background_color", 10, 0),
(375, "Theme - 9", "#FF1D23", "sesatoz_button_background_color_hover", 10, 0),
(376, "Theme - 9", "#FFFFFF", "sesatoz_button_font_color", 10, 0),
(377, "Theme - 9", "#FFFFFF", "sesatoz_button_font_hover_color", 10, 0),
(378, "Theme - 9", "#1E1F23", "sesatoz_comment_background_color", 10, 0),

(379, "Theme - 1", "#F2C71A", "sesatoz_mainmenu_links_background_color_hover", 1, 0),
(380, "Theme - 2", "#D90053", "sesatoz_mainmenu_links_background_color_hover", 2, 0),
(381, "Theme - 3", "#EB1B20", "sesatoz_mainmenu_links_background_color_hover", 3, 0),
(382, "Theme - 4", "#E38700", "sesatoz_mainmenu_links_background_color_hover", 4, 0),
(383, "Theme - 5", "#0396D9", "sesatoz_mainmenu_links_background_color_hover", 6, 0),
(384, "Theme - 6", "#7AAB41", "sesatoz_mainmenu_links_background_color_hover", 7, 0),
(385, "Theme - 7", "#F2C71A", "sesatoz_mainmenu_links_background_color_hover", 8, 0),
(386, "Theme - 8", "#D90053", "sesatoz_mainmenu_links_background_color_hover", 9, 0),
(387, "Theme - 9", "#EB1B20", "sesatoz_mainmenu_links_background_color_hover", 10, 0),
(388, "Theme - 10", "#E38700", "sesatoz_mainmenu_links_background_color_hover", 11, 0),
(389, "Theme - 11", "#0396D9", "sesatoz_mainmenu_links_background_color_hover", 12, 0),
(390, "Theme - 12", "#7AAB41", "sesatoz_mainmenu_links_background_color_hover", 13, 0),
(391, "Theme - 10", "5", "theme_color", 11, 0),
(392, "Theme - 10", "11", "custom_theme_color", 11, 0),
(394, "Theme - 10", "#222428", "sesatoz_header_background_color", 11, 0),
(395, "Theme - 10", "#FF9800", "sesatoz_menu_logo_font_color", 11, 0),
(396, "Theme - 10", "#FF9800", "sesatoz_mainmenu_background_color", 11, 0),
(397, "Theme - 10", "#FFFFFF", "sesatoz_mainmenu_links_color", 11, 0),
(399, "Theme - 10", "#191919", "sesatoz_mainmenu_links_hover_color", 11, 0),
(410, "Theme - 10", "#FFFFFF", "sesatoz_minimenu_links_color", 11, 0),
(411, "Theme - 10", "#FF9800", "sesatoz_minimenu_links_hover_color", 11, 0),
(412, "Theme - 10", "#36383D", "sesatoz_minimenu_icon_background_color", 11, 0),
(413, "Theme - 10", "#FF9800", "sesatoz_minimenu_icon_background_active_color", 11, 0),
(414, "Theme - 10", "#FFFFFF", "sesatoz_minimenu_icon_color", 11, 0),
(415, "Theme - 10", "#191919", "sesatoz_minimenu_icon_active_color", 11, 0),
(416, "Theme - 10", "#36383D", "sesatoz_header_searchbox_background_color", 11, 0),
(417, "Theme - 10", "#FFFFFF", "sesatoz_header_searchbox_text_color", 11, 0),
(418, "Theme - 10", "#FF9800", "sesatoz_toppanel_userinfo_background_color", 11, 0),
(419, "Theme - 10", "#FFFFFF", "sesatoz_toppanel_userinfo_font_color", 11, 0),
(420, "Theme - 10", "#222222", "sesatoz_footer_background_color", 11, 0),
(421, "Theme - 10", "#B3B3B3", "sesatoz_footer_links_color", 11, 0),
(422, "Theme - 10", "#FF9800", "sesatoz_footer_links_hover_color", 11, 0),
(423, "Theme - 10", "#FF9800", "sesatoz_theme_color", 11, 0),
(424, "Theme - 10", "#111418", "sesatoz_body_background_color", 11, 0),
(425, "Theme - 10", "#F1F1F1", "sesatoz_font_color", 11, 0),
(426, "Theme - 10", "#DDDDDD", "sesatoz_font_color_light", 11, 0),
(427, "Theme - 10", "#FFFFFF", "sesatoz_heading_color", 11, 0),
(428, "Theme - 10", "#FFFFFF", "sesatoz_links_color", 11, 0),
(429, "Theme - 10", "#FF9800", "sesatoz_links_hover_color", 11, 0),
(430, "Theme - 10", "#222428", "sesatoz_content_header_background_color", 11, 0),
(431, "Theme - 10", "#FFFFFF", "sesatoz_content_header_font_color", 11, 0),
(432, "Theme - 10", "#222428", "sesatoz_content_background_color", 11, 0),
(433, "Theme - 10", "#36383D", "sesatoz_content_border_color", 11, 0),
(434, "Theme - 10", "#FFFFFF", "sesatoz_form_label_color", 11, 0),
(435, "Theme - 10", "#222428", "sesatoz_input_background_color", 11, 0),
(436, "Theme - 10", "#FFFFFF", "sesatoz_input_font_color", 11, 0),
(437, "Theme - 10", "#36383D", "sesatoz_input_border_color", 11, 0),
(438, "Theme - 10", "#FF9800", "sesatoz_button_background_color", 11, 0),
(439, "Theme - 10", "#FF9800", "sesatoz_button_background_color_hover", 11, 0),
(440, "Theme - 10", "#FFFFFF", "sesatoz_button_font_color", 11, 0),
(441, "Theme - 10", "#FFFFFF", "sesatoz_button_font_hover_color", 11, 0),
(442, "Theme - 10", "#1E1F23", "sesatoz_comment_background_color", 11, 0),
(443, "Theme - 11", "5", "theme_color", 12, 0),
(444, "Theme - 11", "12", "custom_theme_color", 12, 0),
(446, "Theme - 11", "#222428", "sesatoz_header_background_color", 12, 0),
(447, "Theme - 11", "#03A9F4", "sesatoz_menu_logo_font_color", 12, 0),
(448, "Theme - 11", "#03A9F4", "sesatoz_mainmenu_background_color", 12, 0),
(449, "Theme - 11", "#FFFFFF", "sesatoz_mainmenu_links_color", 12, 0),
(451, "Theme - 11", "#191919", "sesatoz_mainmenu_links_hover_color", 12, 0),
(452, "Theme - 11", "#FFFFFF", "sesatoz_minimenu_links_color", 12, 0),
(453, "Theme - 11", "#03A9F4", "sesatoz_minimenu_links_hover_color", 12, 0),
(454, "Theme - 11", "#36383D", "sesatoz_minimenu_icon_background_color", 12, 0),
(455, "Theme - 11", "#03A9F4", "sesatoz_minimenu_icon_background_active_color", 12, 0),
(456, "Theme - 11", "#FFFFFF", "sesatoz_minimenu_icon_color", 12, 0),
(457, "Theme - 11", "#191919", "sesatoz_minimenu_icon_active_color", 12, 0),
(458, "Theme - 11", "#36383D", "sesatoz_header_searchbox_background_color", 12, 0),
(459, "Theme - 11", "#FFFFFF", "sesatoz_header_searchbox_text_color", 12, 0),
(460, "Theme - 11", "#03A9F4", "sesatoz_toppanel_userinfo_background_color", 12, 0),
(461, "Theme - 11", "#FFFFFF", "sesatoz_toppanel_userinfo_font_color", 12, 0),
(462, "Theme - 11", "#222222", "sesatoz_footer_background_color", 12, 0),
(463, "Theme - 11", "#B3B3B3", "sesatoz_footer_links_color", 12, 0),
(464, "Theme - 11", "#03A9F4", "sesatoz_footer_links_hover_color", 12, 0),
(465, "Theme - 11", "#03A9F4", "sesatoz_theme_color", 12, 0),
(466, "Theme - 11", "#111418", "sesatoz_body_background_color", 12, 0),
(467, "Theme - 11", "#F1F1F1", "sesatoz_font_color", 12, 0),
(468, "Theme - 11", "#DDDDDD", "sesatoz_font_color_light", 12, 0),
(469, "Theme - 11", "#FFFFFF", "sesatoz_heading_color", 12, 0),
(470, "Theme - 11", "#FFFFFF", "sesatoz_links_color", 12, 0),
(471, "Theme - 11", "#03A9F4", "sesatoz_links_hover_color", 12, 0),
(472, "Theme - 11", "#222428", "sesatoz_content_header_background_color", 12, 0),
(473, "Theme - 11", "#FFFFFF", "sesatoz_content_header_font_color", 12, 0),
(474, "Theme - 11", "#222428", "sesatoz_content_background_color", 12, 0),
(475, "Theme - 11", "#36383D", "sesatoz_content_border_color", 12, 0),
(476, "Theme - 11", "#FFFFFF", "sesatoz_form_label_color", 12, 0),
(477, "Theme - 11", "#222428", "sesatoz_input_background_color", 12, 0),
(478, "Theme - 11", "#FFFFFF", "sesatoz_input_font_color", 12, 0),
(479, "Theme - 11", "#36383D", "sesatoz_input_border_color", 12, 0),
(480, "Theme - 11", "#03A9F4", "sesatoz_button_background_color", 12, 0),
(481, "Theme - 11", "#FF9800", "sesatoz_button_background_color_hover", 12, 0),
(482, "Theme - 11", "#FFFFFF", "sesatoz_button_font_color", 12, 0),
(483, "Theme - 11", "#FFFFFF", "sesatoz_button_font_hover_color", 12, 0),
(484, "Theme - 11", "#1E1F23", "sesatoz_comment_background_color", 12, 0),
(485, "Theme - 12", "5", "theme_color", 13, 0),
(486, "Theme - 12", "13", "custom_theme_color", 13, 0),
(488, "Theme - 12", "#222428", "sesatoz_header_background_color", 13, 0),
(489, "Theme - 12", "#8BC34A", "sesatoz_menu_logo_font_color", 13, 0),
(490, "Theme - 12", "#8BC34A", "sesatoz_mainmenu_background_color", 13, 0),
(491, "Theme - 12", "#FFFFFF", "sesatoz_mainmenu_links_color", 13, 0),
(493, "Theme - 12", "#191919", "sesatoz_mainmenu_links_hover_color", 13, 0),
(494, "Theme - 12", "#FFFFFF", "sesatoz_minimenu_links_color", 13, 0),
(495, "Theme - 12", "#8BC34A", "sesatoz_minimenu_links_hover_color", 13, 0),
(496, "Theme - 12", "#36383D", "sesatoz_minimenu_icon_background_color", 13, 0),
(497, "Theme - 12", "#8BC34A", "sesatoz_minimenu_icon_background_active_color", 13, 0),
(498, "Theme - 12", "#FFFFFF", "sesatoz_minimenu_icon_color", 13, 0),
(499, "Theme - 12", "#191919", "sesatoz_minimenu_icon_active_color", 13, 0),
(500, "Theme - 12", "#36383D", "sesatoz_header_searchbox_background_color", 13, 0),
(501, "Theme - 12", "#FFFFFF", "sesatoz_header_searchbox_text_color", 13, 0),
(502, "Theme - 12", "#8BC34A", "sesatoz_toppanel_userinfo_background_color", 13, 0),
(503, "Theme - 12", "#FFFFFF", "sesatoz_toppanel_userinfo_font_color", 13, 0),
(504, "Theme - 12", "#222222", "sesatoz_footer_background_color", 13, 0),
(505, "Theme - 12", "#B3B3B3", "sesatoz_footer_links_color", 13, 0),
(506, "Theme - 12", "#8BC34A", "sesatoz_footer_links_hover_color", 13, 0),
(507, "Theme - 12", "#8BC34A", "sesatoz_theme_color", 13, 0),
(508, "Theme - 12", "#111418", "sesatoz_body_background_color", 13, 0),
(509, "Theme - 12", "#F1F1F1", "sesatoz_font_color", 13, 0),
(510, "Theme - 12", "#DDDDDD", "sesatoz_font_color_light", 13, 0),
(511, "Theme - 12", "#FFFFFF", "sesatoz_heading_color", 13, 0),
(512, "Theme - 12", "#FFFFFF", "sesatoz_links_color", 13, 0),
(513, "Theme - 12", "#8BC34A", "sesatoz_links_hover_color", 13, 0),
(514, "Theme - 12", "#222428", "sesatoz_content_header_background_color", 13, 0),
(515, "Theme - 12", "#FFFFFF", "sesatoz_content_header_font_color", 13, 0),
(516, "Theme - 12", "#222428", "sesatoz_content_background_color", 13, 0),
(517, "Theme - 12", "#36383D", "sesatoz_content_border_color", 13, 0),
(518, "Theme - 12", "#FFFFFF", "sesatoz_form_label_color", 13, 0),
(519, "Theme - 12", "#222428", "sesatoz_input_background_color", 13, 0),
(520, "Theme - 12", "#FFFFFF", "sesatoz_input_font_color", 13, 0),
(521, "Theme - 12", "#36383D", "sesatoz_input_border_color", 13, 0),
(522, "Theme - 12", "#8BC34A", "sesatoz_button_background_color", 13, 0),
(523, "Theme - 12", "#8BC34A", "sesatoz_button_background_color_hover", 13, 0),
(524, "Theme - 12", "#FFFFFF", "sesatoz_button_font_color", 13, 0),
(525, "Theme - 12", "#FFFFFF", "sesatoz_button_font_hover_color", 13, 0),
(526, "Theme - 12", "#1E1F23", "sesatoz_comment_background_color", 13, 0);');


$db->query("INSERT IGNORE INTO `engine4_core_settings` (`name`, `value`) VALUES
('sesatoz.banner.bgimage.1', 'public/admin/slide1.jpg'),
('sesatoz.banner.bgimage.2', 'public/admin/slide2.jpg'),
('sesatoz.banner.bgimage.3', 'public/admin/slide3.jpg'),
('sesatoz.banner.bgimage.4', 'public/admin/slide4.jpg'),
('sesatoz.banner.bgimage.5', ''),
('sesatoz.banner.content', 'Share your Photos, Music, Video and let them talk for you.||Join Contests & win exciting prizes and awards.||Create your events and sell tickets online.||Write new Blogs, create Pages, Groups and share your thoughts.'),
('sesatoz.body.background.color', '#ECEFF1'),
('sesatoz.body.background.image', 'public/admin/blank.png'),
('sesatoz.body.fontfamily', 'Georgia, serif'),
('sesatoz.body.fontsize', '14px'),
('sesatoz.button.background.color.hover', '#243238'),
('sesatoz.button.backgroundcolor', '#FB0060'),
('sesatoz.button.font.color', '#FFFFFF'),
('sesatoz.button.font.hover.color', '#FFFFFF'),
('sesatoz.comment.background.color', '#FDFDFD'),
('sesatoz.content.background.color', '#FFFFFF'),
('sesatoz.content.border.color', '#EBECEE'),
('sesatoz.content.header.background.color', '#FFFFFF'),
('sesatoz.content.header.font.color', '#243238'),
('sesatoz.feature.bgimage', 'public/admin/content-circle-bg.jpg'),
('sesatoz.feature.caption', 'Without proper sense of caring, there can be no sense of building Community. We Treasure the relationships here & not the possessions.'),
('sesatoz.feature.content.0.caption', 'Photos & Albums'),
('sesatoz.feature.content.0.description', 'Share your Stories with Photos & let your photos do the talking for you.'),
('sesatoz.feature.content.0.iconimage', 'public/admin/photo-icon.png'),
('sesatoz.feature.content.0.url', 'albums'),
('sesatoz.feature.content.1.caption', 'Join Contests and Win Prizes'),
('sesatoz.feature.content.1.description', 'Join contests by submitting your entries and win many exciting prizes.'),
('sesatoz.feature.content.1.iconimage', 'public/admin/trophy.png'),
('sesatoz.feature.content.1.url', 'contests'),
('sesatoz.feature.content.2.caption', 'Music Albums & Songs'),
('sesatoz.feature.content.2.description', 'What do you want to listen? Choose from awesome collection here.'),
('sesatoz.feature.content.2.iconimage', 'public/admin/music-icon.png'),
('sesatoz.feature.content.2.url', 'music/album/home'),
('sesatoz.feature.content.3.caption', 'Videos, Channels & Playlists'),
('sesatoz.feature.content.3.description', 'We make Videos worth watching. Upload videos & share with the whole world.'),
('sesatoz.feature.content.3.iconimage', 'public/admin/video-icon.png'),
('sesatoz.feature.content.3.url', 'events'),
('sesatoz.feature.content.4.caption', 'Events & Online Booking'),
('sesatoz.feature.content.4.description', 'Create, promote, and host your meetings, conferences, special events, etc.'),
('sesatoz.feature.content.4.iconimage', 'public/admin/event-icon.png'),
('sesatoz.feature.content.4.url', '#'),
('sesatoz.feature.content.5.caption', 'Discover New Groups'),
('sesatoz.feature.content.5.description', 'Join groups based on your interest and get connected with the world.'),
('sesatoz.feature.content.5.iconimage', 'public/admin/group-icon.png'),
('sesatoz.feature.content.5.url', 'groups'),
('sesatoz.feature.heading', 'What''s Our Community For?'),
('sesatoz.font.color.light', '#999999'),
('sesatoz.fontcolor', '#243238'),
('sesatoz.footer.background.color', '#222222'),
('sesatoz.footer.links.color', '#FFFFFF'),
('sesatoz.footer.links.hover.color', '#FB0060'),
('sesatoz.form.label.color', '#243238'),
('sesatoz.googlebody.fontfamily', '\"Roboto\"'),
('sesatoz.googlebody.fontsize', '14px'),
('sesatoz.googlefonts', '1'),
('sesatoz.googleheading.fontfamily', '\"Roboto\"'),
('sesatoz.googleheading.fontsize', '17px'),
('sesatoz.googlemainmenu.fontfamily', '\"Roboto\"'),
('sesatoz.googlemainmenu.fontsize', '13px'),
('sesatoz.googletab.fontfamily', '\"Roboto\"'),
('sesatoz.googletab.fontsize', '15px'),
('sesatoz.header.background.color', '#191919'),
('sesatoz.header.design', '1'),
('sesatoz.header.loggedin.options.0', 'search'),
('sesatoz.header.loggedin.options.1', 'miniMenu'),
('sesatoz.header.loggedin.options.2', 'mainMenu'),
('sesatoz.header.loggedin.options.3', 'logo'),
('sesatoz.header.nonloggedin.options.0', 'search'),
('sesatoz.header.nonloggedin.options.1', 'miniMenu'),
('sesatoz.header.nonloggedin.options.2', 'mainMenu'),
('sesatoz.header.nonloggedin.options.3', 'logo'),
('sesatoz.header.searchbox.background.color', '#ECEFF1'),
('sesatoz.header.searchbox.text.color', '#FFFFFF'),
('sesatoz.header.transparent', '0'),
('sesatoz.heading.color', '#243238'),
('sesatoz.heading.fontfamily', 'Georgia, serif'),
('sesatoz.heading.fontsize', '17px'),
('sesatoz.helpenable', '1'),
('sesatoz.input.background.color', '#FFFFFF'),
('sesatoz.input.border.color', '#CACACA'),
('sesatoz.input.font.color', '#6D6D6D'),
('sesatoz.landingpage.style', '1'),
('sesatoz.latestsection', 'sesalbum_album'),
('sesatoz.latestsectionpop', 'like_count'),
('sesatoz.left.columns.width', '240px'),
('sesatoz.leftcolhdingdes', 'We are a close community to help to meet and greet new people.'),
('sesatoz.leftcolhdingemail', 'info@abc.com'),
('sesatoz.leftcolhdinglocation', 'Los Angeles, USA'),
('sesatoz.leftcolhdingphone', '+91-1234567890'),
('sesatoz.leftcolhdingtext', 'About Us'),
('sesatoz.leftcolumnenable', '1'),
('sesatoz.limit', '8'),
('sesatoz.links.color', '#243238'),
('sesatoz.links.hover.color', '#FB0060'),
('sesatoz.loginsignupbgimage', 'public/admin/blank.png'),
('sesatoz.loginsignuplogo', '0'),
('sesatoz.mainmenu.background.color', '#FB0060'),
('sesatoz.mainmenu.fontfamily', 'Georgia, serif'),
('sesatoz.mainmenu.fontsize', '13px'),
('sesatoz.mainmenu.links.background.color.hover', '#D90053'),
('sesatoz.mainmenu.links.color', '#FFFFFF'),
('sesatoz.mainmenu.links.hover.color', '#FFFFFF'),
('sesatoz.member.infotooltip', '1'),
('sesatoz.member.link', '1'),
('sesatoz.memeber.caption', 'Meet our popular members and grow your network by making friendships with them. Send messages, share posts with them.'),
('sesatoz.memeber.heading', 'Meet Our Popular Members!'),
('sesatoz.memeber.height', '120'),
('sesatoz.memeber.width', '120'),
('sesatoz.menu.img', 'public/admin/blank.png'),
('sesatoz.menu.logo.font.color', '#FB0060'),
('sesatoz.menuinformation.img', 'public/admin/blank.png'),
('sesatoz.minimenu.icon.active.color', '#FFFFFF'),
('sesatoz.minimenu.icon.background.active.color', '#FB0060'),
('sesatoz.minimenu.icon.background.color', '#5D5D5D'),
('sesatoz.minimenu.icon.color', '#FFFFFF'),
('sesatoz.minimenu.links.color', '#FFFFFF'),
('sesatoz.minimenu.links.hover.color', '#FFFFFF'),
('sesatoz.miniuserphotoround', '1'),
('sesatoz.moretext', 'More'),
('sesatoz.popup.day', '5'),
('sesatoz.popup.enable', '1'),
('sesatoz.popupfixed', '0'),
('sesatoz.popupsign', '1'),
('sesatoz.quicklinksenable', '1'),
('sesatoz.responsive.layout', '1'),
('sesatoz.right.columns.width', '240px'),
('sesatoz.rightcolhdingbtn1', 'https://itunes.apple.com/us/app/sesolutions/id1269496435?ls=1&mt=8&ign-mscache=1&ign-msr=https%3A%2F%2Fitunesconnect.apple.com%2FWebObjects%2FiTunesConnect.woa%2Fra%2Fng%2Fapp%2F1269496435'),
('sesatoz.rightcolhdingbtn2', 'https://play.google.com/store/apps/details?id=com.sesolutions&hl=en'),
('sesatoz.rightcolhdingdes', 'We are a secure community with 5000+ active members who help you with your queries, post new updates and grow your network.'),
('sesatoz.rightcolhdingtext', 'Why Join Us?'),
('sesatoz.rightcolumnenable', '1'),
('sesatoz.sidepanel.effect', '2'),
('sesatoz.sidepanel.showhide', '0'),
('sesatoz.socialenable', '1'),
('sesatoz.staticcontent', 'Get connected with your Likeminds'),
('sesatoz.submenu', '1'),
('sesatoz.tab.fontfamily', 'Georgia, serif'),
('sesatoz.tab.fontsize', '15px'),
('sesatoz.theme.color', '#FB0060'),
('sesatoz.toppanel.userinfo.background.color', '#FB0060'),
('sesatoz.toppanel.userinfo.font.color', '#FFFFFF'),
('sesatoz.twitterembed', '<a class=\"twitter-timeline\" data-height=\"400\" data-theme=\"dark\" href=\"https://twitter.com/SocialEngineSol?ref_src=twsrc%5Etfw\">Tweets by SocialEngineSol</a> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>'),
('sesatoz.user.photo.round', '1'),
('sesatoz.youtubevideolink', 'https://www.youtube.com/watch?v=HWPnrgEupPI');");
